import { lazy } from 'react'

// Core TMS — code-split so login and shell load fast
export const Dashboard = lazy(() => import('../pages/Dashboard'))
export const BookingList = lazy(() => import('../pages/booking/BookingList'))
export const NewBooking = lazy(() => import('../pages/booking/NewBooking'))
export const BookingDetails = lazy(() => import('../pages/booking/BookingDetails'))
export const EditBooking = lazy(() => import('../pages/booking/EditBooking'))
export const GenerateLR = lazy(() => import('../pages/lr/GenerateLR'))
export const LRList = lazy(() => import('../pages/lr/LRList'))
export const EditLR = lazy(() => import('../pages/lr/EditLR'))
export const VehicleList = lazy(() => import('../pages/vehicles/VehicleList'))
export const VehicleDetails = lazy(() => import('../pages/vehicles/VehicleDetails'))
export const NewVehicle = lazy(() => import('../pages/vehicles/NewVehicle'))
export const CustomerList = lazy(() => import('../pages/customers/CustomerList'))
export const CustomerDetails = lazy(() => import('../pages/customers/CustomerDetails'))
export const NewCustomer = lazy(() => import('../pages/customers/NewCustomer'))
export const VendorList = lazy(() => import('../pages/vendors/VendorList'))
export const VendorDetails = lazy(() => import('../pages/vendors/VendorDetails'))
export const NewVendor = lazy(() => import('../pages/vendors/NewVendor'))
export const ExpenseList = lazy(() => import('../pages/expenses/ExpenseList'))
export const NewExpense = lazy(() => import('../pages/expenses/NewExpense'))
export const Settings = lazy(() => import('../pages/settings/Settings'))
export const BranchesPage = lazy(() => import('../pages/settings/BranchesPage'))
export const PortalUsersPage = lazy(() => import('../pages/settings/PortalUsersPage'))
export const NotificationSettings = lazy(() => import('../pages/settings/NotificationSettings'))

// Portal
export const PortalLogin = lazy(() => import('../pages/portal/PortalLogin'))
export const PortalLayout = lazy(() => import('../pages/portal/PortalLayout'))
export const PortalDashboard = lazy(() => import('../pages/portal/PortalDashboard'))
export const PortalTrackPage = lazy(() => import('../pages/portal/PortalTrackPage'))
export const PortalInvoices = lazy(() => import('../pages/portal/PortalInvoices'))
export const PortalInvoiceView = lazy(() => import('../pages/portal/PortalInvoiceView'))
export const PortalPublicTrack = lazy(() => import('../pages/portal/PortalPublicTrack'))

// Heavy modules — code-split to reduce initial bundle on low-resource VPS clients
export const AccountingHub = lazy(() => import('../pages/accounting/AccountingHub'))
export const ChartOfAccounts = lazy(() => import('../pages/accounting/ChartOfAccounts'))
export const LedgerMaster = lazy(() => import('../pages/accounting/LedgerMaster'))
export const NewLedger = lazy(() => import('../pages/accounting/NewLedger'))
export const VoucherEntry = lazy(() => import('../pages/accounting/VoucherEntry'))
export const LedgerReport = lazy(() => import('../pages/accounting/LedgerReport'))
export const CustomerLedgerReport = lazy(() => import('../pages/accounting/CustomerLedgerReport'))
export const VendorLedgerReport = lazy(() => import('../pages/accounting/VendorLedgerReport'))
export const DriverLedgerReport = lazy(() => import('../pages/accounting/DriverLedgerReport'))
export const VehicleLedgerReport = lazy(() => import('../pages/accounting/VehicleLedgerReport'))
export const CashBook = lazy(() => import('../pages/accounting/CashBook'))
export const BankBook = lazy(() => import('../pages/accounting/BankBook'))
export const DayBook = lazy(() => import('../pages/accounting/DayBook'))
export const JournalRegister = lazy(() => import('../pages/accounting/JournalRegister'))
export const ReceiptRegister = lazy(() => import('../pages/accounting/ReceiptRegister'))
export const PaymentRegister = lazy(() => import('../pages/accounting/PaymentRegister'))
export const PurchaseRegister = lazy(() => import('../pages/accounting/PurchaseRegister'))
export const SalesRegister = lazy(() => import('../pages/accounting/SalesRegister'))
export const TrialBalance = lazy(() => import('../pages/accounting/TrialBalance'))
export const ProfitLoss = lazy(() => import('../pages/accounting/ProfitLoss'))
export const BalanceSheet = lazy(() => import('../pages/accounting/BalanceSheet'))
export const BookingPaymentAdjustment = lazy(() => import('../pages/accounting/BookingPaymentAdjustment'))
export const ProvisionsPage = lazy(() => import('../pages/accounting/ProvisionsPage'))
export const OutstandingReport = lazy(() => import('../pages/accounting/OutstandingReport'))
export const GSTReports = lazy(() => import('../pages/accounting/GSTReports'))

export const ReportsHub = lazy(() => import('../pages/reports/ReportsHub'))
export const TripReport = lazy(() => import('../pages/reports/TripReport'))
export const VehicleReport = lazy(() => import('../pages/reports/VehicleReport'))
export const DriverReport = lazy(() => import('../pages/reports/DriverReport'))
export const IncomeReport = lazy(() => import('../pages/reports/IncomeReport'))
export const ExpenseReportPage = lazy(() => import('../pages/reports/ExpenseReportPage'))
export const CustomerReport = lazy(() => import('../pages/reports/CustomerReport'))
export const BookingPlReport = lazy(() => import('../pages/reports/BookingPlReport'))
export const BrokerOutstandingReport = lazy(() => import('../pages/reports/BrokerOutstandingReport'))
export const VendorReport = lazy(() => import('../pages/reports/VendorReport'))
export const CashFlowReport = lazy(() => import('../pages/reports/CashFlowReport'))

export const PayrollHub = lazy(() => import('../pages/payroll/PayrollHub'))
export const PayrollList = lazy(() => import('../pages/payroll/PayrollList'))
export const ProcessPayroll = lazy(() => import('../pages/payroll/ProcessPayroll'))
export const PayrollDetails = lazy(() => import('../pages/payroll/PayrollDetails'))
export const PayslipList = lazy(() => import('../pages/payroll/PayslipList'))
export const PayslipView = lazy(() => import('../pages/payroll/PayslipView'))
export const PayrollSettings = lazy(() => import('../pages/payroll/PayrollSettings'))
export const SalaryRegister = lazy(() => import('../pages/payroll/SalaryRegister'))

export const HrHub = lazy(() => import('../pages/hr/HrHub'))
export const EmployeeList = lazy(() => import('../pages/hr/EmployeeList'))
export const EmployeeDetails = lazy(() => import('../pages/hr/EmployeeDetails'))
export const DepartmentList = lazy(() => import('../pages/hr/DepartmentList'))
export const AttendancePage = lazy(() => import('../pages/hr/AttendancePage'))
export const LeaveManagement = lazy(() => import('../pages/hr/LeaveManagement'))
export const HolidaysPage = lazy(() => import('../pages/hr/HolidaysPage'))
export const HrTmsNorms = lazy(() => import('../pages/hr/HrTmsNorms'))

export const FleetMapPage = lazy(() => import('../pages/gps/FleetMapPage'))
export const RouteOptimizerPage = lazy(() => import('../pages/routing/RouteOptimizerPage'))
export const VehicleHistoryPage = lazy(() => import('../pages/gps/VehicleHistoryPage'))
export const GeofenceManagerPage = lazy(() => import('../pages/gps/GeofenceManagerPage'))
export const GeofenceAlertsPage = lazy(() => import('../pages/gps/GeofenceAlertsPage'))
export const OperationsHub = lazy(() => import('../pages/operations/OperationsHub'))

export const FuelPage = lazy(() => import('../pages/operations/ModulePages').then(m => ({ default: m.FuelPage })))
export const EpodPage = lazy(() => import('../pages/operations/ModulePages').then(m => ({ default: m.EpodPage })))
export const CustomerPortalPage = lazy(() => import('../pages/operations/ModulePages').then(m => ({ default: m.CustomerPortalPage })))
export const TripsPage = lazy(() => import('../pages/operations/ModulePages').then(m => ({ default: m.TripsPage })))
export const ShipmentsPage = lazy(() => import('../pages/operations/ModulePages').then(m => ({ default: m.ShipmentsPage })))
export const FinanceModulePage = lazy(() => import('../pages/operations/ModulePages').then(m => ({ default: m.FinanceModulePage })))
export const DocumentsPage = lazy(() => import('../pages/operations/ModulePages').then(m => ({ default: m.DocumentsPage })))
export const NotificationsPage = lazy(() => import('../pages/operations/ModulePages').then(m => ({ default: m.NotificationsPage })))
export const AnalyticsPage = lazy(() => import('../pages/operations/ModulePages').then(m => ({ default: m.AnalyticsPage })))
export const MarketplacePage = lazy(() => import('../pages/operations/ModulePages').then(m => ({ default: m.MarketplacePage })))
export const WarehousePage = lazy(() => import('../pages/operations/ModulePages').then(m => ({ default: m.WarehousePage })))
export const IotPage = lazy(() => import('../pages/operations/ModulePages').then(m => ({ default: m.IotPage })))
export const AiPage = lazy(() => import('../pages/operations/ModulePages').then(m => ({ default: m.AiPage })))

export const PlatformHub = lazy(() => import('../pages/platform/PlatformHub'))
export const MaintenancePage = lazy(() => import('../pages/maintenance/MaintenancePage'))
