/** LR transaction desks — each maps to a workflow stage and pending queue. */
export const LR_OPERATION_MENUS = [
  {
    id: 'lr-management',
    title: 'LR Management',
    description: 'Draft and newly created LRs awaiting review',
    path: '/operations/lr-management',
    icon: 'FileText',
    stage: 'lr-management',
    processStep: null,
  },
  {
    id: 'loading',
    title: 'Loading Management',
    description: 'LRs ready for loading sheet entry',
    path: '/operations/loading',
    icon: 'Package',
    stage: 'loading',
    processStep: 'loading',
  },
  {
    id: 'transit-pass',
    title: 'Transit Pass (Memo)',
    description: 'Loading completed — generate transit pass',
    path: '/operations/transit-pass',
    icon: 'Truck',
    stage: 'transit-pass',
    processStep: 'transit',
  },
  {
    id: 'delivery',
    title: 'Delivery Management',
    description: 'In transit and delivery / POD updates',
    path: '/operations/delivery',
    icon: 'MapPin',
    stage: 'delivery',
    processStep: 'delivery',
  },
  {
    id: 'invoice',
    title: 'Invoice Management',
    description: 'Delivered LRs pending freight invoice',
    path: '/operations/invoice',
    icon: 'Receipt',
    stage: 'invoice',
    processStep: 'invoice',
  },
  {
    id: 'expense',
    title: 'Expense Management',
    description: 'Post-invoice trip expenses to record',
    path: '/operations/lr-expenses',
    icon: 'Wallet',
    stage: 'expense',
    processStep: 'expense',
  },
  {
    id: 'expense-approval',
    title: 'Expense Approval',
    description: 'Pending expense claims awaiting approval',
    path: '/operations/expense-approval',
    icon: 'CheckCircle2',
    stage: 'expense-approval',
    processStep: 'expense',
    isExpenseApproval: true,
  },
  {
    id: 'closing',
    title: 'LR Closing',
    description: 'Invoiced LRs ready for final close',
    path: '/operations/lr-closing',
    icon: 'Lock',
    stage: 'closing',
    processStep: 'close',
  },
]

export function getOperationMenu(stageOrId) {
  return LR_OPERATION_MENUS.find((m) => m.stage === stageOrId || m.id === stageOrId)
}
