import { hubSection, withHubTheme } from './hubTheme'

export const accountingCards = withHubTheme([
  { title: 'Chart of Accounts', path: '/accounting/chart-of-accounts', icon: 'ListTree', description: 'Master list of all ledger accounts' },
  { title: 'Ledger Master', path: '/accounting/ledger-master', icon: 'BookOpen', description: 'Create and manage ledger accounts' },
  { title: 'Voucher List', path: '/accounting/vouchers', icon: 'FileText', description: 'Search, view, edit and delete vouchers' },
  { title: 'Voucher Entry', path: '/accounting/voucher-entry', icon: 'FilePlus', description: 'Record journal, receipt and payment vouchers' },
  { title: 'Ledger Report', path: '/accounting/ledger-report', icon: 'ScrollText', description: 'Account-wise transaction ledger' },
  { title: 'Customer Ledger', path: '/accounting/customer-ledger', icon: 'Users', description: 'Customer account statements' },
  { title: 'Vendor Ledger', path: '/accounting/vendor-ledger', icon: 'Building2', description: 'Vendor account statements' },
  { title: 'Driver Ledger', path: '/accounting/driver-ledger', icon: 'UserCircle', description: 'Driver salary and advance ledger' },
  { title: 'Vehicle Ledger', path: '/accounting/vehicle-ledger', icon: 'Truck', description: 'Vehicle-wise expense and income' },
  { title: 'Cash Book', path: '/accounting/cash-book', icon: 'Banknote', description: 'Daily cash receipts and payments' },
  { title: 'Bank Book', path: '/accounting/bank-book', icon: 'Landmark', description: 'Bank account transactions' },
  { title: 'Day Book', path: '/accounting/day-book', icon: 'CalendarDays', description: 'All vouchers for the day' },
  { title: 'Journal Register', path: '/accounting/journal-register', icon: 'NotebookPen', description: 'Journal voucher register' },
  { title: 'Receipt Register', path: '/accounting/receipt-register', icon: 'Receipt', description: 'All receipt vouchers' },
  { title: 'Payment Register', path: '/accounting/payment-register', icon: 'CreditCard', description: 'All payment vouchers' },
  { title: 'Purchase Register', path: '/accounting/purchase-register', icon: 'ShoppingCart', description: 'Purchase bills register' },
  { title: 'Sales Register', path: '/accounting/sales-register', icon: 'ShoppingBag', description: 'Sales invoices register' },
  { title: 'Freight Invoices', path: '/accounting/freight-invoices', icon: 'FileText', description: 'Freight invoices linked to booking payments' },
  { title: 'Trial Balance', path: '/accounting/trial-balance', icon: 'Calculator', description: 'Debit and credit trial balance' },
  { title: 'Payment Adjustment', path: '/accounting/payment-adjustment', icon: 'IndianRupee', description: 'Record booking outstanding payments' },
  { title: 'Provisions', path: '/accounting/provisions', icon: 'FileStack', description: 'Vendor and party provisions' },
  { title: 'Profit & Loss', path: '/accounting/profit-loss', icon: 'TrendingUp', description: 'Income and expense statement' },
  { title: 'Balance Sheet', path: '/accounting/balance-sheet', icon: 'Scale', description: 'Assets, liabilities and capital' },
  { title: 'Outstanding', path: '/accounting/outstanding', icon: 'AlertCircle', description: 'Receivable and payable outstanding' },
  { title: 'GST Reports', path: '/accounting/gst', icon: 'FileSpreadsheet', description: 'GST input, output and summary' },
  { title: 'TDS Settings', path: '/accounting/tds/settings', icon: 'Settings', description: 'Enable TDS and ledger mapping' },
  { title: 'TDS Sections', path: '/accounting/tds/sections', icon: 'List', description: 'Section codes (194C, 194J, …)' },
  { title: 'TDS Rates', path: '/accounting/tds/rates', icon: 'Percent', description: 'Rates, thresholds and without-PAN rates' },
  { title: 'TDS Exemptions', path: '/accounting/tds/exemptions', icon: 'Shield', description: 'Lower rate / exemption certificates' },
  { title: 'Vendor Payment', path: '/accounting/tds/vendor-payment', icon: 'Wallet', description: 'Pay vendors with TDS payable deduction' },
  { title: 'TDS Transactions', path: '/accounting/tds/transactions', icon: 'History', description: 'Posted TDS history and reversals' },
  { title: 'TDS Reports', path: '/accounting/tds/reports', icon: 'FileBarChart', description: 'Payable, receivable and vendor-wise TDS' },
  { title: 'GL Journal', path: '/accounting/gl/journal', icon: 'BookMarked', description: 'Double-entry journal vouchers with reverse' },
  { title: 'Vendor Bills', path: '/accounting/gl/vendor-bills', icon: 'FileInput', description: 'Vendor bill → payable → settlement' },
  { title: 'Credit / Debit Notes', path: '/accounting/gl/credit-debit-notes', icon: 'FileMinus', description: 'Customer/vendor credit and debit notes' },
  { title: 'Bank Reconciliation', path: '/accounting/gl/bank-recon', icon: 'Landmark', description: 'Bank accounts and statement reconciliation' },
  { title: 'GL Controls', path: '/accounting/gl/controls', icon: 'ShieldCheck', description: 'FY lock, posting maps, migration, audit' },
  { title: 'GST / TDS Compliance', path: '/accounting/gl/compliance', icon: 'FileSpreadsheet', description: 'GSTR-1, GSTR-3B, Form 26Q export, e-Invoice register' },
])

const byPath = Object.fromEntries(accountingCards.map((c) => [c.path, c]))
const pick = (...paths) => paths.map((p) => byPath[p]).filter(Boolean)

export const accountingHubSections = [
  hubSection('Masters & entry', 'Account structure and voucher posting', pick(
    '/accounting/chart-of-accounts',
    '/accounting/ledger-master',
    '/accounting/vouchers',
    '/accounting/voucher-entry',
  ), { chip: 'Entry' }),
  hubSection('Ledgers', 'Party and asset ledgers', pick(
    '/accounting/ledger-report',
    '/accounting/customer-ledger',
    '/accounting/vendor-ledger',
    '/accounting/driver-ledger',
    '/accounting/vehicle-ledger',
  ), { chip: 'Ledger' }),
  hubSection('Books & registers', 'Day books and voucher registers', pick(
    '/accounting/cash-book',
    '/accounting/bank-book',
    '/accounting/day-book',
    '/accounting/journal-register',
    '/accounting/receipt-register',
    '/accounting/payment-register',
    '/accounting/purchase-register',
    '/accounting/sales-register',
    '/accounting/freight-invoices',
  ), { chip: 'Book' }),
  hubSection('Statements & compliance', 'Financial statements and outstanding', pick(
    '/accounting/trial-balance',
    '/accounting/profit-loss',
    '/accounting/balance-sheet',
    '/accounting/outstanding',
    '/accounting/payment-adjustment',
    '/accounting/provisions',
    '/accounting/gst',
  ), { chip: 'Report' }),
  hubSection('TDS', 'Tax deducted at source — masters, payments and reports', pick(
    '/accounting/tds/settings',
    '/accounting/tds/sections',
    '/accounting/tds/rates',
    '/accounting/tds/exemptions',
    '/accounting/tds/vendor-payment',
    '/accounting/tds/transactions',
    '/accounting/tds/reports',
  ), { chip: 'TDS' }),
  hubSection('Double-entry GL', 'Posting engine, AP bills, banking and controls', pick(
    '/accounting/gl/journal',
    '/accounting/gl/vendor-bills',
    '/accounting/gl/credit-debit-notes',
    '/accounting/gl/bank-recon',
    '/accounting/gl/controls',
    '/accounting/gl/compliance',
  ), { chip: 'GL' }),
]
