export const navigation = [
  { title: 'Dashboard', path: '/', icon: 'LayoutDashboard', feature: 'dashboard' },
  {
    title: 'Shipment Management',
    path: '/shipment-management',
    icon: 'Package',
    feature: 'lr',
    matchPrefixes: [
      '/shipment-management',
      '/bookings',
      '/lr',
      '/operations/loading-slip',
      '/operations/transit-pass',
      '/operations/dispatch',
      '/operations/hub-transfer',
    ],
    excludePrefixes: ['/lr/expense-approval'],
  },
  {
    title: 'Delivery Management',
    path: '/delivery-management',
    icon: 'PackageCheck',
    feature: 'lr',
    matchPrefixes: [
      '/delivery-management',
      '/operations/in-transit',
      '/operations/delivery-complete',
      '/operations/delivery/pod',
    ],
  },
  {
    title: 'Billing',
    path: '/operations/billing/list',
    icon: 'Receipt',
    feature: 'lr',
    matchPrefix: '/operations/billing',
  },
  {
    title: 'Operations',
    path: '/operations',
    icon: 'Layers',
    feature: 'lr',
    matchPrefix: '/operations',
    excludePrefixes: [
      '/operations/loading-slip',
      '/operations/transit-pass',
      '/operations/dispatch',
      '/operations/in-transit',
      '/operations/delivery-complete',
      '/operations/delivery/pod',
      '/operations/trip-expenses',
      '/operations/billing',
    ],
  },
  { title: 'Accounts', path: '/accounting', icon: 'Calculator', feature: 'accounting', matchPrefix: '/accounting' },
  { title: 'Reports', path: '/reports', icon: 'BarChart3', feature: 'dashboard', matchPrefix: '/reports' },
  { title: 'Masters', path: '/masters', icon: 'Database', matchPrefix: '/masters' },
  { title: 'Maintenance', path: '/maintenance', icon: 'Wrench', matchPrefix: '/maintenance' },
  {
    title: 'Expenses',
    path: '/expenses',
    icon: 'Wallet',
    matchPrefixes: ['/expenses', '/operations/trip-expenses', '/lr/expense-approval'],
  },
  { title: 'HR & Payroll', path: '/hr', icon: 'Briefcase', matchPrefixes: ['/hr', '/payroll'] },
  { title: 'Settings', path: '/settings', icon: 'Settings', matchPrefix: '/settings' },
]

export const platformNavigation = [
  { title: 'Platform Admin', path: '/platform', icon: 'Shield' },
]
